main: Wars.AncapWars.AncapWars
name: AncapWars
version: beta-1.0
api-version: 1.16

depend:
  - AncapStates

commands:
  war:
    description:
    permission:
    usage: "Usage: /<command>"
  castle:
    description:
    permission:
    usage: "Usage: /<command>"