# взносы
fees:
  castle:
    creation:
      start:
        netherite: 3
      raising:
        netherite: 0.25

hexagon:
  health:
    normal: 12000
    debug: 25

castle:
  assault:
    time:
      normal: 3600
      debug: 30
  core:
    max-height: 172
  health: 
    normal: 100
    debug: 3